# Generated by Django 6.0 on 2026-01-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersession',
            new_name='accounts_us_user_id_b0e444_idx',
            old_name='accounts_usersession_user_login_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='accounts_us_token_j_7ef2e4_idx',
            old_name='accounts_usersession_token_jti_idx',
        ),
    ]
