# Development Dockerfile for Backend
FROM python:3.13-slim

WORKDIR /app

# Install system dependencies
RUN apt-get install -y --no-install-recommends gcc

# Install pipenv
RUN pip install --no-cache-dir pipenv

# Expose port
EXPOSE 8000

# Start development server
CMD ["entrypoint.dev.sh"]