# Generated by Django 6.0 on 2025-12-25 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reportnote_savedreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedreport',
            name='unique_saved_report',
        ),
        migrations.AlterUniqueTogether(
            name='savedreport',
            unique_together={('report_type', 'period_type', 'jalali_year', 'jalali_month', 'jalali_week', 'user', 'domain')},
        ),
    ]
